version: '3'
services:
  app:
    container_name: react_study_app
    build:
      context: .
      dockerfile: ./Src_React/Dockerfile
    environment:
      - WATCHPACK_POLLING=true
    volumes:
    - ./Src_React/react-app:/usr/src/app
    #"react-app"の部分がプロジェクト名になる
    command: sh -c "cd /usr/src/app && yarn start" 
    ports:
      - 3000:3000
    stdin_open: true #標準入力をコンテナと紐付ける
  